# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Rails Fever | Application Modernization Consultancy
email: info@railsfever.com
description: >- # this means to ignore newlines until "baseurl:"
  Rails Fever provides long-term maintenance, support, upgrades, performance and security services for Rails apps.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://railsfever.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ""
github_username:  waleo

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

# Blog settings
paginate: 6
paginate_path: "/blog/page/:num/"
permalink: /blog/:title/

schedule_meeting_link: https://calendly.com/wale/30-minute-consultation

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - BLOG-IMAGES-GUIDE.md
  - CLAUDE.md
  - assets/images/blog/README.md
  - _posts/2024-10-10-debugging-legacy-rails-apps.md
  - _posts/2024-11-28-rails-performance-optimization.md
  - _posts/2024-12-15-upgrading-rails-7-to-8.md
  - _posts/YYYY-MM-DD-post-template.md
